title: 'Chopstick'
author: 'Wijs'
description: 'Chopstick is a design framework based on the ITCSS architecture and a series of principles. It creates a structure to easily set-up and build bespoke web projects. Combined with Jekyll and Gulp you have a prototyping tool that enables you to quickly create high-fidelity prototypes, marketing sites and blogs.'
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
